### ISSUE TITLE
Не устанавливается pylab

### ISSUE THREAD

**Issue by Jayms17** [vkantor/MIPT_Data_Mining_In_Action_2016#15]
Здравствуйте. У меня Mac OS X El Capitan. На попытку установить pylab  терминал выдаёт: Collecting pylab:
Collecting pylon Could not find a version that satisfies the requirement pylab (from versions: )
No matching distribution found for pylab.
Либо если через Анаконду:
Jayms17-2:~ Anna$ conda install pylab
Fetching package metadata ......
Solving package specifications: .
PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels: 
- pylab

Close matches found; did you mean one of these?

```
pylab: impyla
```

You can search for packages on anaconda.org with

```
anaconda search -t conda pylab
```

И я не знаю как это обойти. Подскажите, пожалуйста, что делать?

**Comment by senya-ashukha** [comment]
sudo pip2 install scipy numpy matplotlib ipython[all] --upgrade

**Comment by Jayms17** [comment]
Опять ошибку выдает(

Jayms17-2:~ Anna$ sudo pip2 install scipy numpy matplotlib ipython[all] --upgrade
Password:
The directory '/Users/Anna/Library/Logs/pip' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Anna/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
You are using pip version 6.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/Users/Anna/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting scipy
  Downloading scipy-0.18.1.tar.gz (13.1MB)
    100% |████████████████████████████████| 13.1MB 37kB/s 
    Complete output from command python setup.py egg_info:
    Running from numpy source directory.
    /tmp/easy_install-HmJwUU/numpy-1.11.2/setup.py:327: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command, proceeding with "
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    non-existing path in 'numpy/distutils': 'site.cfg'
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable f90
    Could not locate executable f77
    Could not locate executable xlf90
    Could not locate executable xlf
    Could not locate executable ifort
    Could not locate executable ifc
    Could not locate executable g77
    Could not locate executable g95
    Could not locate executable pgfortran
    don't know how to compile Fortran code on platform 'posix'
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-DFARXG/scipy/setup.py", line 415, in <module>
        setup_package()
      File "/private/tmp/pip-build-DFARXG/scipy/setup.py", line 411, in setup_package
        setup(**metadata)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 310, in fetch_build_eggs
        replace_conflicting=True,
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/**init**.py", line 830, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1075, in best_match
        return self.obtain(req, installer)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1087, in obtain
        return installer(requirement)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 377, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1056, in run_setup
        run_setup(setup_script, args)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 240, in run_setup
        raise
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in **exit**
        self.gen.throw(type, value, traceback)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in **exit**
        self.gen.throw(type, value, traceback)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 164, in save_modules
        saved_exc.resume()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 139, in resume
        compat.reraise(type, exc, self._tb)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 152, in save_modules
        yield saved
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 237, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 267, in run
        return func()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 236, in runner
        _execfile(setup_script, ns)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-HmJwUU/numpy-1.11.2/setup.py", line 386, in <module>
        # Raise errors for unsupported commands, improve help output, etc.
      File "/tmp/easy_install-HmJwUU/numpy-1.11.2/setup.py", line 378, in setup_package
        test_suite='nose.collector',
      File "/tmp/easy_install-HmJwUU/numpy-1.11.2/numpy/distutils/core.py", line 169, in setup
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 151, in run
        self.run_command("egg_info")
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-HmJwUU/numpy-1.11.2/numpy/distutils/command/egg_info.py", line 18, in run
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/easy_install-HmJwUU/numpy-1.11.2/numpy/distutils/command/build_src.py", line 147, in run
      File "/tmp/easy_install-HmJwUU/numpy-1.11.2/numpy/distutils/command/build_src.py", line 158, in build_sources
      File "/tmp/easy_install-HmJwUU/numpy-1.11.2/numpy/distutils/command/build_src.py", line 293, in build_library_sources
      File "/tmp/easy_install-HmJwUU/numpy-1.11.2/numpy/distutils/command/build_src.py", line 376, in generate_sources
      File "numpy/core/setup.py", line 653, in get_mathlib_info

```
RuntimeError: Broken toolchain: cannot link a simple C program

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-DFARXG/scipy
```

**Comment by senya-ashukha** [comment]
Смотри, первое что нужно делать -- вставлять ошибку в гугл

http://g.zeos.in/?q=RuntimeError%3A%20Broken%20toolchain%3A%20cannot%20link%20a%20simple%20C%20program&m=1 

Напиши вышло или нет?

**Comment by Jayms17** [comment]
Это первое, что я сделал - прогуглил. Просто я уже выдохся и ничего не понял в итоге, что там все советуют.

**Comment by senya-ashukha** [comment]
Первый вариант у Вас гцц не установлен, если нету brew, то он просто
ставится -- brew install gcc
Второй вариант, нужно попробовать с хитрыми флагами sudo ARCHFLAGS=-Wno-
error=unused-command-line-argument-hard-error-in-future pip install --upgrade
numpy

**Comment by Jayms17** [comment]
Спасибо, до завтра попытаюсь разобраться и отпишусь.

**Comment by Jayms17** [comment]
Установил gcc, опять не работало. Заменил в итоге строчку %pylab inline на import pylab и тут наконец стало работать)
